" vim: fdm=marker ts=2 sts=2 sw=2 fdl=0
if &compatible
  set nocompatible
endif

nnoremap ; :
nnoremap : ;

function! s:get_cache_dir(suffix)
	return resolve(expand('~/.vim/.cache/' . a:suffix))
endfunction

set timeoutlen=300
set ttimeoutlen=50
set history=1000
set viewoptions=folds,options,cursor,unix,slash
set encoding=utf-8
set hidden
set autoread
set nrformats-=octal
set showcmd
set tags=tags;/
set showfulltag
set modeline
set modelines=5
set noshelltemp
set backspace=indent,eol,start
set autoindent
set smarttab

let &tabstop=2
let &softtabstop=2
let &shiftwidth=2

set shiftround
set linebreak

set scrolloff=1
set scrolljump=5
set display+=lastline
set wildmenu
set wildmode=list:full
set wildignorecase

set splitbelow
set splitright
set noerrorbells
set novisualbell
set t_vb=

set hlsearch
set incsearch
set ignorecase
set smartcase

set undofile
let &undodir = s:get_cache_dir('undo')
set backup
let &backupdir = s:get_cache_dir('backup')

let &directory = s:get_cache_dir('swap')
set noswapfile
set expandtab

function! EnsureExists(path)
  if !isdirectory(expand(a:path))
    call mkdir(expand(a:path))
  endif
endfunction

call EnsureExists('~/.vim/.cache')
call EnsureExists(&undodir)
call EnsureExists(&backupdir)
call EnsureExists(&directory)

let mapleader = ","
let g:mapleader = ","

augroup TerminalStuff
  au!
  autocmd TermOpen * setlocal nonumber norelativenumber
augroup END

set showmatch
set matchtime=2
set number
set lazyredraw
set laststatus=2
set noshowmode
set foldenable
set foldmethod=syntax
set foldlevelstart=99
let g:xml_syntax_folding=1
