# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  hardware.enableRedistributableFirmware = true;
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cc6ab80a-be0c-4890-9128-ce906e1bc970";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2874c98c-d6f5-49d5-b106-0c8471366a84".device = "/dev/disk/by-uuid/2874c98c-d6f5-49d5-b106-0c8471366a84";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/17A3-5EBE";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3cdbb21d-b01d-4e86-98f1-9543d7178584"; }
    ];

  nix.maxJobs = lib.mkDefault 16;
}
